import { useCallback, useRef, useState } from 'react';
import {
  FlatList,
  KeyboardAvoidingView,
  Linking,
  Platform,
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';

import { BiText } from '../../components/ui/BiText';
import { Card } from '../../components/ui/Card';
import { Icon } from '../../components/ui/Icon';
import { useAuth } from '../../context/AuthContext';
import { useT } from '../../i18n/useT';
import { trackEvent } from '../../lib/analytics';
import { supabase } from '../../lib/supabase';
import { colors, radius, spacing } from '../../theme/tokens';
import { typography, urduTypography } from '../../theme/typography';

type Lang = 'en' | 'ur';

type ChatMsg = {
  id: string;
  role: 'user' | 'assistant';
  text: string;
};

type FaqHit = {
  question_en: string;
  question_ur: string | null;
  answer_en: string;
  answer_ur: string | null;
  score?: number;
};

const SUPPORT_EMAIL = 'support@workerzpk.local';

const introEn =
  'Ask a short question. Answers come only from our curated FAQ — nothing is generated by an AI model.';
const introUr =
  'ایک مختصر سوال پوچھیں۔ جواب صرف ہمارے تیار کردہ FAQ سے آتے ہیں — کوئی AI ماڈل جواب نہیں بناتا۔';

export default function FaqChatScreen() {
  const { session } = useAuth();
  const userId = session?.user.id ?? null;
  const listRef = useRef<FlatList<ChatMsg>>(null);
  const { t } = useT();

  const [lang, setLang] = useState<Lang>('en');
  const [input, setInput] = useState('');
  const [busy, setBusy] = useState(false);
  const [messages, setMessages] = useState<ChatMsg[]>([
    { id: 'intro', role: 'assistant', text: introEn },
  ]);

  const pushAssistant = useCallback((text: string) => {
    setMessages((m) => [...m, { id: `${Date.now()}-a`, role: 'assistant', text }]);
  }, []);

  const send = async () => {
    const q = input.trim();
    if (!q || busy) return;
    setInput('');
    setBusy(true);
    void trackEvent('faq_chat_message', userId, { q });
    setMessages((m) => [...m, { id: `${Date.now()}-u`, role: 'user', text: q }]);

    try {
      const { data, error } = await supabase.rpc('search_faqs', { p_query: q, p_limit: 3 });
      if (error || !Array.isArray(data) || data.length === 0) {
        const noMatch =
          lang === 'en'
            ? 'I could not find a matching FAQ entry. Tap below to email support.'
            : 'مماثل FAQ نہیں ملا۔ نیچے سپورٹ کو ای میل کرنے کے لیے ٹیپ کریں۔';
        pushAssistant(noMatch);
        void trackEvent('faq_chat_no_match', userId, { q });
        return;
      }

      const top = data[0] as FaqHit;
      const answer = lang === 'ur' && top.answer_ur ? top.answer_ur : top.answer_en;
      const title = lang === 'ur' && top.question_ur ? top.question_ur : top.question_en;
      pushAssistant(`${title}\n\n${answer}`);
      void trackEvent('faq_chat_answered', userId, { q, score: top.score ?? null });
    } finally {
      setBusy(false);
      requestAnimationFrame(() => listRef.current?.scrollToEnd({ animated: true }));
    }
  };

  const contactSupport = () => {
    const url = `mailto:${SUPPORT_EMAIL}?subject=${encodeURIComponent('WorkerzPk support (chat)')}`;
    void trackEvent('faq_chat_support_handoff', userId, {});
    void Linking.openURL(url);
  };

  return (
    <KeyboardAvoidingView
      style={styles.flex}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      keyboardVerticalOffset={80}
    >
      <FlatList
        ref={listRef}
        data={messages}
        keyExtractor={(item) => item.id}
        contentContainerStyle={styles.list}
        onContentSizeChange={() => listRef.current?.scrollToEnd({ animated: true })}
        ListHeaderComponent={
          <Card padding="lg">
            <BiText id="faqChat.title" variant="title" tone="strong" />
            <BiText id="faqChat.intro" variant="bodySm" tone="muted" style={styles.cardSubtitle} />
            <View style={styles.langRow}>
              {(['en', 'ur'] as Lang[]).map((l) => {
                const active = lang === l;
                return (
                  <Pressable
                    key={l}
                    accessibilityRole="button"
                    onPress={() => {
                      setLang(l);
                      setMessages((m) =>
                        m.map((row) =>
                          row.id === 'intro'
                            ? { ...row, text: l === 'en' ? introEn : introUr }
                            : row
                        )
                      );
                    }}
                    style={[styles.langBtn, active && styles.langBtnActive]}
                  >
                    <Text style={[styles.langText, active && styles.langTextActive]}>
                      {l === 'en' ? 'English' : 'اردو'}
                    </Text>
                  </Pressable>
                );
              })}
            </View>
          </Card>
        }
        renderItem={({ item }) => {
          const isUser = item.role === 'user';
          return (
            <View style={[styles.bubbleWrap, isUser ? styles.bubbleWrapUser : styles.bubbleWrapBot]}>
              <View style={[styles.bubble, isUser ? styles.bubbleUser : styles.bubbleBot]}>
                <Text style={[styles.bubbleText, isUser && styles.bubbleTextUser]}>{item.text}</Text>
              </View>
            </View>
          );
        }}
      />
      <View style={styles.composer}>
        <View style={styles.composerRow}>
          <TextInput
            value={input}
            onChangeText={setInput}
            placeholder={t('faqChat.placeholder').en}
            placeholderTextColor={colors.textMuted}
            style={styles.input}
            multiline
            editable={!busy}
          />
          <Pressable
            onPress={send}
            disabled={busy || !input.trim()}
            accessibilityRole="button"
            accessibilityLabel={t('faqChat.send').en}
            style={[styles.sendBtn, (busy || !input.trim()) && styles.sendBtnDisabled]}
          >
            <Icon name="send" size={18} color={colors.primaryInk} />
          </Pressable>
        </View>
        <Text style={styles.urduPlaceholder}>{t('faqChat.placeholder').ur}</Text>
        <Pressable onPress={contactSupport} style={styles.supportLink} accessibilityRole="button">
          <Icon name="mail" size={14} color={colors.primary} />
          <Text style={styles.supportLinkText}>{t('faqChat.emailSupport').en}</Text>
          <Text style={styles.supportLinkUr}>{t('faqChat.emailSupport').ur}</Text>
        </Pressable>
      </View>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.bg },
  list: { padding: spacing.lg, paddingBottom: spacing.sm },
  cardSubtitle: { marginTop: spacing.sm, marginBottom: spacing.md },
  langRow: { flexDirection: 'row', gap: spacing.sm },
  langBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.divider,
  },
  langBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  langText: { ...typography.button, color: colors.textStrong },
  langTextActive: { color: colors.primaryInk },
  bubbleWrap: { marginBottom: spacing.sm, width: '100%' },
  bubbleWrapUser: { alignItems: 'flex-end' },
  bubbleWrapBot: { alignItems: 'flex-start' },
  bubble: {
    maxWidth: '88%',
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  bubbleUser: { backgroundColor: colors.primary, borderBottomRightRadius: radius.xs },
  bubbleBot: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.divider,
    borderBottomLeftRadius: radius.xs,
  },
  bubbleText: { ...typography.body, color: colors.textBody },
  bubbleTextUser: { color: colors.primaryInk },
  composer: {
    padding: spacing.lg,
    paddingBottom: spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    backgroundColor: colors.surface,
  },
  composerRow: { flexDirection: 'row', gap: spacing.sm, alignItems: 'flex-end' },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    minHeight: 48,
    maxHeight: 120,
    ...typography.body,
    color: colors.textStrong,
    backgroundColor: colors.surface,
  },
  sendBtn: {
    width: 48,
    height: 48,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: { opacity: 0.5 },
  urduPlaceholder: {
    ...urduTypography.caption,
    color: colors.textMuted,
    textAlign: 'right',
    writingDirection: 'rtl',
    marginTop: 4,
  },
  supportLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    gap: 6,
  },
  supportLinkText: { ...typography.button, color: colors.primary },
  supportLinkUr: { ...urduTypography.button, color: colors.primary, marginLeft: 6 },
});
